name: ClearML ML Model CI/CD Pipeline

on:
  pull_request:
    branches: [master]
    types: [assigned, opened, edited, reopened, synchronize]

jobs:
  train-and-monitor:
    runs-on: ubuntu-20.04
    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      CLEARML_WEB_HOST: ${{ secrets.CLEARML_WEB_HOST }}
      CLEARML_FILES_HOST: ${{ secrets.CLEARML_FILES_HOST }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      COMMIT_ID: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Launch Training Task
        run: |
          python launch_training_task.py
      - name: Read Task ID
        id: task_id
        run: |
          echo "TASK_ID=$(cat task_id.txt)" >> $GITHUB_ENV
      - name: Poll for Task Progress
        run: |
          python check_clearml_task_running.py ${{ env.TASK_ID }}
      - name: Fetch Task Statistics and Create PR Comment
        run: |
          python create_stats_comment.py ${{ env.TASK_ID }}